### ISSUE TITLE
Where is secretMethod?

### ISSUE THREAD

**Issue by jaredrummler** [maldroid/samples#1]
Interesting stuff. How did you hide it? Explanation anywhere?

**Comment by maldroid** [comment]
Yup: http://maldr0id.blogspot.com/2014/09/sandroid-rat-analysis-part-i-synthetic.html :)

**Comment by jaredrummler** [comment]
Interesting. The blog post didn't give a solid example. Is there an example
I can look at? Thanks.

On Wed, Mar 4, 2015 at 1:08 PM, maldroid notifications@github.com wrote:

> Yup:
> http://maldr0id.blogspot.com/2014/09/sandroid-rat-analysis-part-i-synthetic.html
> :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maldroid/samples/issues/1#issuecomment-77247603.

## 

Jared Rummler | CEO at JRummy Apps Inc http://www.jrummyapps.com/. |
jared.rummler@gmail.com

https://www.facebook.com/JRummyApps  https://twitter.com/jrummy16
https://plus.google.com/u/0/+JaredRummler/posts
http://www.linkedin.com/pub/jared-rummler/40/ba2/77a
http://instagram.com/jaredrummler  http://www.youtube.com/user/jrummy16
https://play.google.com/store/apps/developer?id=JRummy+Apps+Inc.

**Comment by maldroid** [comment]
This sample you mentioned is the minimal working example - see the smali & jd-gui generated code and compare.
